// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ksl_sentence_recognition.proto
#ifndef GRPC_ksl_5fsentence_5frecognition_2eproto__INCLUDED
#define GRPC_ksl_5fsentence_5frecognition_2eproto__INCLUDED

#include "ksl_sentence_recognition.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace vision {
namespace raw {
namespace v1 {

class SequenceService final {
 public:
  static constexpr char const* service_full_name() {
    return "vision.raw.v1.SequenceService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::vision::raw::v1::Frame>> SendFrames(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::vision::raw::v1::Frame>>(SendFramesRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::vision::raw::v1::Frame>> AsyncSendFrames(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::vision::raw::v1::Frame>>(AsyncSendFramesRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::vision::raw::v1::Frame>> PrepareAsyncSendFrames(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::vision::raw::v1::Frame>>(PrepareAsyncSendFramesRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendFrames(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::ClientWriteReactor< ::vision::raw::v1::Frame>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::vision::raw::v1::Frame>* SendFramesRaw(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::vision::raw::v1::Frame>* AsyncSendFramesRaw(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::vision::raw::v1::Frame>* PrepareAsyncSendFramesRaw(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::vision::raw::v1::Frame>> SendFrames(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::vision::raw::v1::Frame>>(SendFramesRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::vision::raw::v1::Frame>> AsyncSendFrames(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::vision::raw::v1::Frame>>(AsyncSendFramesRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::vision::raw::v1::Frame>> PrepareAsyncSendFrames(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::vision::raw::v1::Frame>>(PrepareAsyncSendFramesRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendFrames(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::ClientWriteReactor< ::vision::raw::v1::Frame>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::vision::raw::v1::Frame>* SendFramesRaw(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response) override;
    ::grpc::ClientAsyncWriter< ::vision::raw::v1::Frame>* AsyncSendFramesRaw(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::vision::raw::v1::Frame>* PrepareAsyncSendFramesRaw(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendFrames_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendFrames(::grpc::ServerContext* context, ::grpc::ServerReader< ::vision::raw::v1::Frame>* reader, ::vision::raw::v1::SubmitResultResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendFrames() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFrames(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::vision::raw::v1::Frame>* /*reader*/, ::vision::raw::v1::SubmitResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendFrames(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::vision::raw::v1::SubmitResultResponse, ::vision::raw::v1::Frame>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendFrames<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendFrames() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::vision::raw::v1::Frame, ::vision::raw::v1::SubmitResultResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, ::vision::raw::v1::SubmitResultResponse* response) { return this->SendFrames(context, response); }));
    }
    ~WithCallbackMethod_SendFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFrames(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::vision::raw::v1::Frame>* /*reader*/, ::vision::raw::v1::SubmitResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::vision::raw::v1::Frame>* SendFrames(
      ::grpc::CallbackServerContext* /*context*/, ::vision::raw::v1::SubmitResultResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendFrames<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendFrames() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFrames(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::vision::raw::v1::Frame>* /*reader*/, ::vision::raw::v1::SubmitResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendFrames() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFrames(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::vision::raw::v1::Frame>* /*reader*/, ::vision::raw::v1::SubmitResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendFrames(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendFrames() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->SendFrames(context, response); }));
    }
    ~WithRawCallbackMethod_SendFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFrames(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::vision::raw::v1::Frame>* /*reader*/, ::vision::raw::v1::SubmitResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* SendFrames(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace v1
}  // namespace raw
}  // namespace vision


#endif  // GRPC_ksl_5fsentence_5frecognition_2eproto__INCLUDED
