// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ksl_sentence_recognition.proto

#include "ksl_sentence_recognition.pb.h"
#include "ksl_sentence_recognition.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace vision {
namespace raw {
namespace v1 {

static const char* SequenceService_method_names[] = {
  "/vision.raw.v1.SequenceService/SendFrames",
};

std::unique_ptr< SequenceService::Stub> SequenceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SequenceService::Stub> stub(new SequenceService::Stub(channel, options));
  return stub;
}

SequenceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendFrames_(SequenceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::vision::raw::v1::Frame>* SequenceService::Stub::SendFramesRaw(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::vision::raw::v1::Frame>::Create(channel_.get(), rpcmethod_SendFrames_, context, response);
}

void SequenceService::Stub::async::SendFrames(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::ClientWriteReactor< ::vision::raw::v1::Frame>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::vision::raw::v1::Frame>::Create(stub_->channel_.get(), stub_->rpcmethod_SendFrames_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::vision::raw::v1::Frame>* SequenceService::Stub::AsyncSendFramesRaw(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::vision::raw::v1::Frame>::Create(channel_.get(), cq, rpcmethod_SendFrames_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::vision::raw::v1::Frame>* SequenceService::Stub::PrepareAsyncSendFramesRaw(::grpc::ClientContext* context, ::vision::raw::v1::SubmitResultResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::vision::raw::v1::Frame>::Create(channel_.get(), cq, rpcmethod_SendFrames_, context, response, false, nullptr);
}

SequenceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SequenceService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< SequenceService::Service, ::vision::raw::v1::Frame, ::vision::raw::v1::SubmitResultResponse>(
          [](SequenceService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::vision::raw::v1::Frame>* reader,
             ::vision::raw::v1::SubmitResultResponse* resp) {
               return service->SendFrames(ctx, reader, resp);
             }, this)));
}

SequenceService::Service::~Service() {
}

::grpc::Status SequenceService::Service::SendFrames(::grpc::ServerContext* context, ::grpc::ServerReader< ::vision::raw::v1::Frame>* reader, ::vision::raw::v1::SubmitResultResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vision
}  // namespace raw
}  // namespace v1

