# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ksl_sentence_recognition.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ksl_sentence_recognition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eksl_sentence_recognition.proto\x12\rvision.raw.v1\")\n\x06Point3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\x9f\x01\n\x05\x46rame\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0c\n\x04\x66lag\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\x0c\n\x04type\x18\x06 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x12*\n\x0bpose_points\x18\x08 \x03(\x0b\x32\x15.vision.raw.v1.Point3\"P\n\x14SubmitResultResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66rame_count\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\\\n\x0fSequenceService\x12I\n\nSendFrames\x12\x14.vision.raw.v1.Frame\x1a#.vision.raw.v1.SubmitResultResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ksl_sentence_recognition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT3']._serialized_start=49
  _globals['_POINT3']._serialized_end=90
  _globals['_FRAME']._serialized_start=93
  _globals['_FRAME']._serialized_end=252
  _globals['_SUBMITRESULTRESPONSE']._serialized_start=254
  _globals['_SUBMITRESULTRESPONSE']._serialized_end=334
  _globals['_SEQUENCESERVICE']._serialized_start=336
  _globals['_SEQUENCESERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
